# Generated by Django 3.2.13 on 2022-05-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
